# Configuration for Black.

[tool.black]
exclude = '''
      \.git
    | \.github
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | plugin\.py
    | tests
'''
line-length = 100
target-version = ['py33', 'py38']
target_version = ['py33', 'py38']
