name: CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python:
          - '3.3'
          - '3.8'
        arch:
          - 'x64'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install test suites
        run: pip install -r tests/requirements.txt
      - name: Run flake8
        run: python -m flake8
      - name: Run pytest
        run: python -m pytest --import-mode=append tests/
      - name: Run black
        run: python -m black --check .
        if: ${{ matrix.python == '3.8' }}
