name: CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  workflow_dispatch:

jobs:
  lint:
    name: lint code using python ${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python:
          - '3.3'
          - '3.8'
        arch:
          - 'x64'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install linters
        run: pip install -r tests/requirements.txt
      - name: Run black
        run: python -m black --check .
        if: ${{ matrix.python == '3.8' }}
      - name: Run flake8
        run: python -m flake8

  test:
    name: run tests using Sublime Text ${{ matrix.st_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        st_version: [3, 4]
    container:
      image: sublimetext/unittesting
      options: --cap-add=NET_ADMIN
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.st_version }}
    steps:
      - uses: actions/checkout@v1
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests
